# Generated by Django 3.1.7 on 2021-03-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminModel',
        ),
    ]
