# Generated by Django 3.1.7 on 2021-03-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('orderitems', models.CharField(max_length=10)),
            ],
        ),
    ]
