# Generated by Django 3.1.7 on 2021-03-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='orderstatus',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
